### PR TITLE
#495 Run format lint in pre commit

### PR DESCRIPTION
**Pull request by Raymans**
#495
Running format-lint first, and then run format-lint by per-commit hook before every committing. you will get error if any lint error happened.

After this, developers won't need to worry about forgetting format-lint before committing by manually.

### CODE REVIEW

**Comment by Raymans** [comment]
It's better to review and merge this first, due to format-lint entire files, easily get conflicts if other changes happened.

**Comment by Darper** [comment]
This is awesome. Can't believe we had so many files escape linting. I hadn't even thought about linting test files, but that'll help a lot too.

**Comment by Darper** [comment]
I updated my node_modules and attempted to make a commit to this branch. Got the following message. Am I missing a step?

```
$ git commit -a -m "testing commit hook"
: No such file or directory 2: ./node_modules/pre-commit/hook
: integer expression expected: [: 127
: numeric argument required 5: exit: 0
```

**Comment by hbowden** [comment]
@Raymans Thanks, awesome pull request, this will be really nice, we should also have something similar for the new app.

**Comment by Raymans** [comment]
I've used a new fresh branch to install, build and commit which still worked perfectly, not sure what you went through.

image

**Pull request merged**
