### PR TITLE
Update babel to use babel-preset-env (#500)

### PR DESCRIPTION
**Pull request by bwilliams-un**

### CODE REVIEW

**Comment by Darper** [comment]
When attempting to build your branch I get the following error. Do  I need to nuke node_modules or anything, or should this just work?

```
ERROR in ./src/index.js
Module build failed: Error: Couldn't find preset "env" relative to directory "C:\\dev\\react-atlas"
    at C:\dev\react-atlas\packages\react-atlas-core\node_modules\babel-core\lib\transformation\file\options\option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (C:\dev\react-atlas\packages\react-atlas-core\node_modules\babel-core\lib\transformation\file\options\option-manag
er.js:275:20)
    at OptionManager.mergePresets (C:\dev\react-atlas\packages\react-atlas-core\node_modules\babel-core\lib\transformation\file\options\option-manager
.js:264:10)
    at OptionManager.mergeOptions (C:\dev\react-atlas\packages\react-atlas-core\node_modules\babel-core\lib\transformation\file\options\option-manager
.js:249:14)
    at OptionManager.init (C:\dev\react-atlas\packages\react-atlas-core\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:
12)
    at File.initOptions (C:\dev\react-atlas\packages\react-atlas-core\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (C:\dev\react-atlas\packages\react-atlas-core\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (C:\dev\react-atlas\packages\react-atlas-core\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (C:\dev\react-atlas\packages\react-atlas-core\node_modules\babel-loader\lib\index.js:50:20)
    at Object.module.exports (C:\dev\react-atlas\packages\react-atlas-core\node_modules\babel-loader\lib\index.js:175:20)
 @ multi ./src/index.js
```

**Comment by bwilliams-un** [comment]
@darper You should just have to run a npm install on root to get the latest packages. I tested both build and build:prd when setting it up and ran all tests and they succeeded. What steps did you perform?

**Comment by Darper** [comment]
My bad. I shouldn't be doing reviews at midnight. Forgot to npm install. I'll try again.

**Comment by Darper** [comment]
Looks great.

**Pull request merged**
