### PR TITLE
Implements Nav Component.

### PR DESCRIPTION
**Pull request by Raymans**
#489 Implements Navigation Component
layout follows https://www.digitalriver.com/styleguide/navigation.php?nav=4

### CODE REVIEW

**Comment by Raymans** [comment]
Rendering via JSON data

**Comment by Darper** [comment]
Found an issue with this component when running a production build. Nav.js uses ...

`if (child.type.name === "Nav" || child.type.displayName === "Nav")`

... but both name and displayName are uglified by a prod build to something like "a" or "t" instead of "Nav". I'm looking for an alternative.

**Comment by Darper** [comment]
Please replace line 93 with `if (typeof child.props.children === "object") {`

I've tested this and confirmed it works with prod builds. Also, can you add `margin-top: 0;` to your .nav class in Nav.css?

After that, looks good to merge.

**Comment by Darper** [comment]
Requested changes implemented in PR #866 
Good work on this!

**Pull request closed without merging**
